#!/bin/busybox sh
#
# /init        ... is the first program, the kernel launches.
#                  It executes
# /bin/init    ... which on the other hand reads
# /etc/inittab ... which calls first
#    /etc/init.d/rc.S
#              ... and second respawns
#    login console(s).
# After login the shell (ash) executes ~/.profile.


exec /bin/init
