#!/bin/busybox sh

source /etc/global-variables
source /etc/key-query


### LOCAL VARIABLES
STATUSLINE=1
STATUSCOLOR=$BGBLUE


### MAIN PROGRAM

set -m # turn jobcontrol on

sleep 100 &
clear
jobs

echo -n "${CSI}$STATUSLINE;1H$STATUSCOLOR"

while :
do
 _get_key

 case "$_KEY" in
  'LEFT') bg %1 ;;
  'RIGHT') fg %1 ;;
  'UP') echo up;;
  'DOWN') echo down ;;

  'ENTER') ps ;;

  'TAB') jobs
echo -n "${CSI}$STATUSLINE;1H$STATUSCOLOR"
  ;;

  q|Q|0|'ESC') break ;;
 esac
done

kill %1
kill %2
kill %3
