#!/bin/busybox sh

### INCLUDE FILES
HEADERDIR="/etc/headers"
source $HEADERDIR/global-variables
source $HEADERDIR/key-query
source $HEADERDIR/global-functions

_printkeyboard(){
 CURPOSY=$MENULINE
 KBLINE=1
 while [ $KBLINE -le $KBLINES ]; do
  eval a=\$KB$KBLINE; _printmenuentrys $a
  CURPOSY=$(($CURPOSY + 1)); 
  KBLINE=$(($KBLINE + 1))
 done
}


### MAIN PROGRAM

LINE=1
CHOOSE=1
CURPOSY=$MENULINE;

_printkeyboard

while :; do

 CURPOSY=$(($LINE + $(($MENULINE - 1)))); eval a=\$KB$LINE;  _menu $a
 RETCHAR=${RETVAL:0:1}
 RETNR=${RETVAL:1:2}

echo retchar $RETCHAR retval $RETNR line $LINE

 case "$RETCHAR" in
  "u") echo up
   eval a=\$KB$LINE; _printmenuentrys $a # print line w/o entry
   LINE=$(($LINE - 1))
   if [ $LINE -le 0 ]; then LINE=$KBLINES; fi
  ;;
  "d") echo down
   eval a=\$KB$LINE; _printmenuentrys $a # print line w/o entry
   LINE=$(($LINE + 1))
  if [ $LINE -gt $KBLINES ]; then LINE=1; fi
  ;;
 esac

# CURPOSY=$LINE
#echo lin $LINE

# if [ $RETCHAR == "u" ]; then LINE=$(($LINE - 1))
#  if [ $LINE -le 1 ]; then LINE=$KBLINES; fi
# else
# if [ $RETCHAR == "d" ]; then LINE=$(($LINE + 1))
#  if [ $LINE -gt $KBLINES ]; then LINE=1; fi
#  else
#   xy=1
#  fi
# fi

# if [ $CHOOSE -le 1 ]; then CHOOSE=$#
#   else CHOOSE=$(($CHOOSE - 1))
#   fi ;;


 case "$RETNR" in
  '0') break ;;
  '1') echo new ;;
  '2') echo goto ;;
  '3') echo kill ;;
  '4') break ;;
 esac
done

#while :; do
# _get_key
# case "$_KEY" in
#  'LEFT') echo left ;;
#  'RIGHT') echo right ;;
#  'UP') echo up;;
#  'DOWN') echo down ;;
#  "$OK") echo OK ;;
#  "$KO") echo KO ;;
##  q|Q|0|'ESC') break ;;
# esac
#done
#   if [ $CHOOSE -le 1 ]; then CHOOSE=$#
#   else CHOOSE=$(($CHOOSE - 1))
#   fi ;;
#  'RIGHT')
#   if [ $CHOOSE -ge $# ]; then CHOOSE=1
#   else CHOOSE=$(($CHOOSE + 1))
#   fi ;;
