#!/bin/sh
##!/bin/busybox sh

set -m

while :; do
 echo -n "Input (1job 2sh 3shApp 4fg 5bg 0off):"; read n

 case "$n" in
  "0") break ;;
  "1") echo "jobs:"; jobs ;;
  "2") exec sh &
   echo "back"
   ;;
  "3") shellApp &
   echo "back"
   ;;
  "4") fg ;;
  "5") bg ;;
 esac
done
