#!/bin/busybox sh
#
# Tray is the main program that manages background processes (Apps)
# and desktop applications (Widgets).

### INCLUDE FILES
HEADERDIR="/etc/headers"
source $HEADERDIR/global-variables
source $HEADERDIR/key-query
source $HEADERDIR/global-functions


### MAIN PROGRAM

set -m
CHOOSE=1; 

clear

while :; do
#clear
 # print/call pseudo widgets on desktop
  clockWidget

 _menu $TRAYMENU
 NR=${RETVAL:1:2}
 case "$NR" in
  '0') break ;;
  '1') echo "jobs:"; jobs ;;
  '2') fg ;;
  '3') bg ;;
  '4') shellApp & ;;
  '5') break ;;
 esac
done


#while :; do
# clear
# _menu $TRAYMENU
# NR=${RETVAL:1:2}
# case "$NR" in
#  '0') break ;;
#  '1') echo "jobs:"; jobs ;;
#  '2') exec sh & ;;
#  '3') fg ;;
#  '4') bg ;;
#  '5') shellApp & 
#clear
#echo "back in tray"
#;;
#  '6') break ;;
# esac
#done